name: buster

on:
  push:
    branches:
      - 'buster'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Debian package
        uses: dawidd6/action-debian-package@v1
        with:
          # Optional, relative to workspace directory
          #source_directory: ot-br-posix/ot-br-posix
          # Optional, relative to workspace directory
          #artifacts_directory: output
          # Optional, value from `debian/changelog` is used if not defined
          #os_distribution: buster
          # Optional, target architecture, defaults to amd64
          cpu_architecture: armhf
